title: IP Community
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://IPcommunity.github.io

aux_links:
  GitHub: https://github.com/IPcommunity

sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ['import'] # https://github.com/just-the-docs/just-the-docs/issues/1607

markdown: kramdown