title: 8th IP Workshop
description: The website of the 8th International Induced Polarization Workshop
theme: bulma-clean-theme

permalink: pretty


force_theme: light

aux_links:
  GitHub: https://github.com/IPcommunity

sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ['import'] # https://github.com/just-the-docs/just-the-docs/issues/1607

markdown: kramdown

# Pagination settings
paginate: 5
paginate_path: "/blog/page:num"
