title: 8th IP Workshop
description: A starter template for a Jeykll site using the Just the Docs theme!
remote_theme: just-the-docs

aux_links:
  GitHub: https://github.com/IPcommunity

sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ['import'] # https://github.com/just-the-docs/just-the-docs/issues/1607

markdown: kramdown