title: 8th IP Workshop
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: ""
baseurl: ""  # Empty if you're no longer using a subpath like /ipworkshop2026

aux_links:
  GitHub: https://github.com/IPcommunity

sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ['import'] # https://github.com/just-the-docs/just-the-docs/issues/1607

markdown: kramdown